# Generated by Django 5.2.8 on 2025-11-24 09:24

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SatelliteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('original_image', models.FileField(help_text='Upload GeoTIFF satellite imagery', upload_to='satellite/original/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['tif', 'tiff', 'geotiff'])])),
                ('optimized_image', models.FileField(blank=True, help_text='Cloud-optimized GeoTIFF (COG)', null=True, upload_to='satellite/optimized/%Y/%m/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='satellite/thumbnails/%Y/%m/')),
                ('bounds', django.contrib.gis.db.models.fields.PolygonField(blank=True, geography=True, null=True, srid=4326)),
                ('center_point', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('acquisition_date', models.DateTimeField(blank=True, help_text='Date when the satellite captured this image', null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('resolution', models.FloatField(blank=True, help_text='Ground sample distance in meters', null=True)),
                ('bands', models.IntegerField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('file_size', models.BigIntegerField(blank=True, help_text='Size in bytes', null=True)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('optimized', 'Optimized'), ('failed', 'Failed')], db_index=True, default='uploaded', max_length=20)),
                ('processing_error', models.TextField(blank=True)),
                ('analyzed', models.BooleanField(db_index=True, default=False)),
                ('analysis_count', models.IntegerField(default=0)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Satellite Image',
                'verbose_name_plural': 'Satellite Images',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('threat_detection', 'Threat Detection'), ('change_detection', 'Change Detection'), ('object_recognition', 'Object Recognition'), ('terrain_analysis', 'Terrain Analysis')], db_index=True, max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, help_text='Human-readable summary of analysis results')),
                ('raw_data', models.JSONField(default=dict, help_text='Detailed analysis data in JSON format')),
                ('confidence_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('threat_count', models.IntegerField(default=0)),
                ('processing_time', models.FloatField(blank=True, help_text='Processing time in seconds', null=True)),
                ('error_message', models.TextField(blank=True)),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('satellite_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='satellite.satelliteimage')),
            ],
            options={
                'verbose_name': 'Analysis Result',
                'verbose_name_plural': 'Analysis Results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ThreatDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threat_type', models.CharField(choices=[('explosion', 'Explosion/Bomb Blast'), ('fire', 'Fire/Smoke'), ('armed_group', 'Armed Group Activity'), ('vehicle_convoy', 'Vehicle Convoy'), ('structural_damage', 'Structural Damage'), ('unusual_activity', 'Unusual Activity'), ('camp_formation', 'Camp Formation'), ('roadblock', 'Roadblock/Checkpoint')], db_index=True, max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='medium', max_length=20)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('pixel_coordinates', models.JSONField(help_text='Pixel coordinates in the original image')),
                ('area', django.contrib.gis.db.models.fields.PolygonField(blank=True, geography=True, null=True, srid=4326)),
                ('confidence', models.FloatField(help_text='Detection confidence score (0-1)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('description', models.TextField(help_text='Plain language description for military personnel')),
                ('technical_details', models.JSONField(default=dict, help_text='Technical analysis details')),
                ('detected_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_threats', to=settings.AUTH_USER_MODEL)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='satellite.analysisresult')),
                ('satellite_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threats', to='satellite.satelliteimage')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_threats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Threat Detection',
                'verbose_name_plural': 'Threat Detections',
                'ordering': ['-detected_at', '-severity'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=20)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='satellite.analysisresult')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['analysis', '-timestamp'], name='satellite_a_analysi_7303dd_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='satelliteimage',
            index=models.Index(fields=['-upload_date', 'status'], name='satellite_s_upload__acb980_idx'),
        ),
        migrations.AddIndex(
            model_name='satelliteimage',
            index=models.Index(fields=['analyzed', '-upload_date'], name='satellite_s_analyze_10e545_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisresult',
            index=models.Index(fields=['-created_at', 'status'], name='satellite_a_created_779d89_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisresult',
            index=models.Index(fields=['satellite_image', '-created_at'], name='satellite_a_satelli_3d0041_idx'),
        ),
        migrations.AddIndex(
            model_name='threatdetection',
            index=models.Index(fields=['-detected_at', 'severity'], name='satellite_t_detecte_a1be67_idx'),
        ),
        migrations.AddIndex(
            model_name='threatdetection',
            index=models.Index(fields=['threat_type', '-detected_at'], name='satellite_t_threat__6fe36d_idx'),
        ),
        migrations.AddIndex(
            model_name='threatdetection',
            index=models.Index(fields=['verified', '-detected_at'], name='satellite_t_verifie_57c84a_idx'),
        ),
    ]
